### ISSUE TITLE
problems while doplying api in digital-ocean platform using mysql as database

### ISSUE THREAD

**Issue by Tiganimohammad** [schoolofcode-me/rest-api-sections#11]
in addition nginx in showed msg in the broswer 404 Not Found
i still google to fix them........and please if you add tut how to use MySQL instead of PostgreSQL but also you can help..thanks in advance sir Jose

*** Starting uWSGI 2.0.16 (64bit) on [Thu Feb 22 11:39:09 2018] ***
compiled with version: 5.4.0 20160609 on 22 February 2018 09:17:09
os: Linux-4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018
nodename: Flask-Api-Test
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
dropping root privileges as early as possible
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3913
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
dropping root privileges after socket binding
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Set PythonHome to /var/www/html/items-rest/venv
Python main interpreter initialized at 0x2066f80
dropping root privileges after plugin initialization
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
*** has_emperor mode detected (fd: 6) ***
unable to load configuration from uwsgi

**Comment by jslvtr** [comment]
Hey Tiago, thanks for raising! This is a problem with the deployment and not with the code in here—could you ask any questions in the Course Q&A or through our Slack channel?

It seems the uwsgi.ini file is missing. Let's pick it up in the Course Q&A.
