### ISSUE TITLE
circular dependency section 6

### ISSUE THREAD

**Issue by mickaelmarin** [schoolofcode-me/rest-api-sections#12]
Hi,

In section 6 of your course, you spoke about circular dependency, but I don't understand why.
I try to put 'from db import db' at the top of the app.py file and it work without errors.

Could you explain brieffly, in which case this circular dependency happen ?

thanks,

Mickael

**Comment by CristianoYL** [comment]
Hi Mickael,

The circular import will happen if we put the `db` module inside `app.py` instead of `db.py`, since in that case, other models need to import `db` from `app.py`, however, we also import those models in `app.py`, and this will lead to the circular import.

**Comment by jslvtr** [comment]
Hey Mickael,

Thanks for raising this—I think you may be right and the import statement can be anywhere within that file. I will investigate!
