### ISSUE TITLE
Small typo in the "How To Deploy Python App Using uWSGI And Nginx" guide

### ISSUE THREAD

**Issue by davidmikulis** [schoolofcode-me/rest-api-sections#21]
The guide is [located here](https://github.com/schoolofcode-me/rest-api-sections/blob/master/guides/How%20To%20Deploy%20Python%20App%20Using%20uWSGI%20And%20Nginx.md).

> After it is installed, we can create a virtualenv:
>
> virtualenv venv --python==python3.5

From looking at the virtualenv documentation, I believe it should be a single equals sign in the command.
`virtualenv venv --python=python3.5`

This is a great guide, thank you!

**Comment by CristianoYL** [comment]
@davidmikulis Thank you for pointing it out and sorry for the confusion. You're right. Would you like to make a PR for it?

**Comment by davidmikulis** [comment]
Sure thing, just created it!

**Comment by jslvtr** [comment]
Merged! Thank you David.
